# Generated by Django 4.2.9 on 2026-05-12 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=30, verbose_name="Segment au moment de l'offre")),
                ('rank', models.IntegerField(default=0, verbose_name='Classement (1=meilleur)')),
                ('gift_type', models.CharField(choices=[('discount', 'Réduction (%)'), ('product', 'Article gratuit'), ('shipping', 'Livraison offerte'), ('points', 'Points fidélité'), ('voucher', "Bon d'achat (DT)")], max_length=20, verbose_name='Type de cadeau')),
                ('gift_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valeur (% ou DT)')),
                ('gift_details', models.TextField(verbose_name="Description de l'offre")),
                ('admin_note', models.TextField(blank=True, verbose_name='Note interne admin')),
                ('valid_days', models.IntegerField(default=7, verbose_name='Durée de validité (jours)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', "En attente d'envoi"), ('sent', 'Email envoyé'), ('accepted', 'Acceptée par le client'), ('declined', 'Refusée par le client'), ('expired', 'Expirée')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Token sécurisé (lien email)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_offers', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Offre cadeau',
                'verbose_name_plural': 'Offres cadeaux',
                'db_table': 'analytics_giftoffer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recency_days', models.IntegerField(help_text='Jours depuis le dernier achat')),
                ('frequency', models.IntegerField(help_text='Nombre de commandes total')),
                ('monetary', models.DecimalField(decimal_places=3, help_text='Montant total dépensé (DT)', max_digits=12)),
                ('avg_order_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('cluster_id', models.IntegerField(default=0)),
                ('segment', models.CharField(choices=[('champions', '🏆 Champions'), ('loyaux', '💙 Loyaux'), ('a_risque', '⚠️ À risque'), ('perdus', '❌ Perdus'), ('nouveau', '🆕 Nouveau')], db_index=True, max_length=30)),
                ('segment_label', models.CharField(blank=True, max_length=60)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de calcul')),
                ('model_version', models.CharField(default='kmeans_ss_v1_k4', max_length=30, verbose_name='Version du modèle')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Segment client',
                'verbose_name_plural': 'Segments clients',
                'db_table': 'analytics_customersegment',
                'ordering': ['cluster_id', '-monetary'],
                'indexes': [models.Index(fields=['cluster_id'], name='analytics_c_cluster_48164c_idx'), models.Index(fields=['segment'], name='analytics_c_segment_407fc8_idx'), models.Index(fields=['-monetary'], name='analytics_c_monetar_0ba06a_idx')],
            },
        ),
    ]
