# Generated by Django 4.2.9 on 2026-05-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersegment',
            name='segment',
            field=models.CharField(choices=[('champions', '🏆 Champions'), ('loyaux', '💙 Loyaux'), ('a_risque_perdus', '⚠️ À risque / Perdus')], db_index=True, max_length=30),
        ),
    ]
